//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiltrData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPoints
    {
        public int CheckPointId { get; set; }
        public Nullable<bool> Drinks { get; set; }
        public Nullable<bool> EnergyBars { get; set; }
        public Nullable<bool> Toilets { get; set; }
        public Nullable<bool> Information { get; set; }
        public Nullable<bool> Medicial { get; set; }
    }
}
