//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiltrData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speed
    {
        public string Name { get; set; }
        public byte[] Picture { get; set; }
        public string Top_Speed { get; set; }
    }
}
